/**
 * The QR the home page shows — a real one.
 *
 * Both forms below encode `QR_PAYLOAD`: the join URL the CLI puts in its
 * banner, `<app origin>/j#<code>` (see `joinUrl()` in
 * `apps/cli/src/commands/start.ts`). It is a real, scannable code, generated by
 * the same encoder at the same error-correction level the CLI uses — the demo
 * code it carries is long expired, so scanning it lands on the pairing page
 * and says so, which is the honest outcome and not a broken picture.
 *
 * This file is generated. To change the payload, edit `PAYLOAD` in
 * `scripts/generate-qr.mjs` and run `node scripts/generate-qr.mjs`.
 *
 * - `QR_MATRIX` is the module grid, one string per row, "1" = dark module.
 *   `<QrCode>` draws it as an SVG, which is what the hero uses.
 * - `QR_ROWS` is the half-block rendering `qrcode-terminal` emits in small
 *   mode — literally what lands in your scrollback — used by the demo cast so
 *   the replayed terminal shows the same bytes a real one would.
 *
 * Each row is the same length by construction, checked by `player.test.ts`,
 * because a ragged row would visibly shear the block.
 */

/** What the code encodes. The join URL the CLI prints, with the demo code. */
export const QR_PAYLOAD = "https://app.mtmux.com/j#492716384";

/** 29×29 modules. "1" is a dark module, "0" a light one. */
export const QR_MATRIX: readonly string[] = [
  "11111110110000011111101111111",
  "10000010000000110000001000001",
  "10111010100111110000101011101",
  "10111010110100001111001011101",
  "10111010111101000101101011101",
  "10000010010010100101101000001",
  "11111110101010101010101111111",
  "00000000010101100110000000000",
  "11110010100001101100010011101",
  "10010001110000011001111110001",
  "11111111100000110110011110110",
  "10011001000111110000111110001",
  "01010010110100000111000001100",
  "10000101101101000011011100111",
  "10001111011010101001111000111",
  "11011100111011011001010010010",
  "01010111000100001000110011010",
  "01000100010011011010100101110",
  "10010011101110010110001010100",
  "00011101000010000101010100100",
  "01011111111111010100111111100",
  "00000000110011100000100011111",
  "11111110010111001011101011010",
  "10000010011000011011100011011",
  "10111010000010111110111110110",
  "10111010100110110110110011001",
  "10111010111101001001110100101",
  "10000010111100101001100111010",
  "11111110111010101001110100010",
];

/** 16 rows of half-blocks — one glyph per two QR modules vertically. */
export const QR_ROWS: readonly string[] = [
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
  "█ ▄▄▄▄▄ █▄▄████▀ ▄▄▄▄▄█ ▄▄▄▄▄ █",
  "█ █   █ █ ▀█ ▄▄▄▄▀▀▀▀▄█ █   █ █",
  "█ █▄▄▄█ █▄ ▄▄▀▄▀██ █  █ █▄▄▄█ █",
  "█▄▄▄▄▄▄▄█▄▀▄▀▄▀ █▄▀ █▄█▄▄▄▄▄▄▄█",
  "█ ▄▄ ██▄▀ ▀███▄▄▀ ▄█▀▀ ▀▀ ▄▄█ █",
  "█ ▄▄  ▄▄ ▄██▀▀▀  █▄▄█▀    █▄▄▀█",
  "█▀▄█▄█▀▄▀ ▄▀ █▀███▄  █▀▀▀█▄ ▀▀█",
  "█ ▀█▀  ▄▄▀  █ ▀▄▀ ██ ▄ ▄█▀█▄ ▄█",
  "██ █▄█ ▄▄█▀█▄▀▀█▀ █▀█ ▄█▀▄ ▀ ██",
  "█▄██ ▀▀▄ ▄█▄▄ ██▄█ ▄▀█▀▄▀▄█ ███",
  "██▄█▄▄▄▄▄  ▄▄  ▀▄█▄██ ▄▄▄   ▀▀█",
  "█ ▄▄▄▄▄ ██ ▀▄▄▄█▀ █   █▄█  █ ▀█",
  "█ █   █ █▀██▀ █  ▄  █  ▄▄ ▀▄▄▀█",
  "█ █▄▄▄█ █    █▄▀█ ██  ▄█ ▀▀▄▀▄█",
  "█▄▄▄▄▄▄▄█▄▄▄█▄█▄█▄██▄▄▄█▄███▄██",
];

export const QR_WIDTH = QR_ROWS[0]?.length ?? 0;
