/**
 * The QR the home page shows — a real one.
 *
 * Both forms below encode `QR_PAYLOAD`: the join URL the CLI puts in its
 * banner, `<app origin>/j#<code>` (see `joinUrl()` in
 * `apps/cli/src/commands/start.ts`). It is a real, scannable code, generated by
 * the same encoder at the same error-correction level the CLI uses — the demo
 * code it carries is long expired, so scanning it lands on the pairing page
 * and says so, which is the honest outcome and not a broken picture.
 *
 * This file is generated. To change the payload, edit `PAYLOAD` in
 * `scripts/generate-qr.mjs` and run `node scripts/generate-qr.mjs`.
 *
 * - `QR_MATRIX` is the module grid, one string per row, "1" = dark module.
 *   `<QrCode>` draws it as an SVG, which is what the hero uses.
 * - `QR_ROWS` is the half-block rendering `qrcode-terminal` emits in small
 *   mode — literally what lands in your scrollback — used by the demo cast so
 *   the replayed terminal shows the same bytes a real one would.
 *
 * Each row is the same length by construction, checked by `player.test.ts`,
 * because a ragged row would visibly shear the block.
 */

/** What the code encodes. The join URL the CLI prints, with the demo code. */
export const QR_PAYLOAD = "https://app.mtmux.com/j#482913";

/** 25×25 modules. "1" is a dark module, "0" a light one. */
export const QR_MATRIX: readonly string[] = [
  "1111111011111100001111111",
  "1000001001011100001000001",
  "1011101010000100101011101",
  "1011101011000110101011101",
  "1011101011000011101011101",
  "1000001001001000001000001",
  "1111111010101010101111111",
  "0000000001010000100000000",
  "1111001010011010010011101",
  "0110010101011100110100010",
  "1010101010010100110110000",
  "0110000100010110000101100",
  "1111001111000110011010111",
  "0011100001100111101110001",
  "0111001100000110100010110",
  "1011100010101011101110001",
  "0000101111101110111111111",
  "0000000010110001100010101",
  "1111111001101110101010111",
  "1000001000111001100010011",
  "1011101001001010111111011",
  "1011101011011100001011111",
  "1011101010111111111010110",
  "1000001011010100011010100",
  "1111111010101100000111111",
];

/** 14 rows of half-blocks — one glyph per two QR modules vertically. */
export const QR_ROWS: readonly string[] = [
  "▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄",
  "█ ▄▄▄▄▄ █▄ ▄   ████ ▄▄▄▄▄ █",
  "█ █   █ █ ▀███ ▀█ █ █   █ █",
  "█ █▄▄▄█ █▄ ██▀█▄▄▄█ █▄▄▄█ █",
  "█▄▄▄▄▄▄▄█▄▀▄▀▄█▄█ █▄▄▄▄▄▄▄█",
  "█▄  ▄█▀▄▀▄▀█  ▀▄█▀ █▀▄▄▄▀▄█",
  "█▄▀ █▄█▄▀▄██ █ ▀█▄▄█ ▄▀▀███",
  "█▄▄  ▀█▄▄▄ ▀██  ▀▀▄ ▀ █▄▄ █",
  "█▀▄  ▀█▄▄▀█▀█▀▄ ▀ █▀▀ █▄▄▀█",
  "█████▄█▄▄ ▄ ▀▄▄▄▀ ▄▄▄ ▄ ▄ █",
  "█ ▄▄▄▄▄ ██▄ ▀ ▄▄▀ █▄█ █▄  █",
  "█ █   █ █▀ █▀ ▀▄█▄▄ ▄  ▀  █",
  "█ █▄▄▄█ █ ▀▄ ▄ ▄▄▄  █ █ ▄██",
  "█▄▄▄▄▄▄▄█▄█▄█▄▄█████▄▄▄▄▄▄█",
];

export const QR_WIDTH = QR_ROWS[0]?.length ?? 0;
